### ISSUE TITLE
screenshots of

### ISSUE THREAD

**Issue by msulemanjaved82** [msulemanjaved82/quizapp5m223#3]
1) result
2) history

**Comment by HammadYaseen666** [comment]
"History Screen"

![Screenshot 2024-01-03 140831](https://github.com/msulemanjaved82/quizapp5m223/assets/147861270/18e30298-358e-477d-be15-bce515136a9c)

**Comment by HammadYaseen666** [comment]
"Result Screens"
![Screenshot 2024-01-03 145324](https://github.com/msulemanjaved82/quizapp5m223/assets/147861270/5452ddb9-9d4c-4b2b-9c3f-8f3d431fd5d7)
![Screenshot 2024-01-03 145356](https://github.com/msulemanjaved82/quizapp5m223/assets/147861270/060caf55-09b3-49d5-8dd7-7f22724bc339)
